spring:
  application:
    name: Assignment Ticket Service Application
  main:
    web-environment: false
    
hold-expiry-duration: 30
row-count: 5
column-count: 5
    
logging:
  file: ./logs/${spring.application.name}